Wahlprojekt/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from start import views

from django.contrib.auth import views as auth_views
#Sammlung der Urls aus unseren erstellten Apps
urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Alle urls aus unserer App start werden eingebunden
    path('', include('start.urls')),
    path('', include('home.urls')),
    path('', include('edit.urls')),
    
    #Passwort vergessen
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='start/password_reset.html'), name='reset_password'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='start/password_reset_done.html'), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='start/password_reset_confirm.html'), name='password_reset_confirm'),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(template_name='start/password_reset_complete.html'), name='password_reset_complete'),
]

edit/urls.py
from django.urls.conf import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'edit'
urlpatterns = [
    #User ruft den Pfad auf, der im ersten Parameter steht
    #danach wird View im 2.Parameter geladen, die in der Datei Views.py steht
    #Die Index View gibt unsere main.html Datei zurück
    #Name ist das, was im Browser angezeigt wird unter Pfad
    path('setttings/', views.settings, name='settings'),
    path('editBankData/', views.editBankData, name='editBankData'),
    path('deleteAccount/', views.deleteAccount, name='deleteAccount'),
    path('editReceipts/', views.editReceipts, name='editReceipts'),
    path('editContacts/', views.editContacts, name='editContacts'),
    path('editBankAccount/', views.editBankAccount, name='editBankAccount'),
    path('editToDos/', views.editToDos, name='editToDos'),
    path('change_password_form', auth_views.PasswordChangeView.as_view(template_name='edit/change_password_form.html', success_url=reverse_lazy('edit:password_change_done')), name='change_password_form'),
    path('password_change_done', auth_views.PasswordChangeDoneView.as_view(template_name='edit/change_password_done.html'), name='password_change_done'),
]

home/urls.py
from django.urls.conf import path
from . import views

app_name = 'home'
urlpatterns = [
    #User ruft den Pfad auf, der im ersten Parameter steht
    #danach wird View im 2.Parameter geladen, die in der Datei Views.py steht
    #Die Index View gibt unsere main.html Datei zurück
    #Name ist das, was im Browser angezeigt wird unter Pfad
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('accounts/', views.accounts, name='accounts'),
    path('accountDetails/', views.accountDetails, name='accountDetails'),
    path('receipts/', views.receipts, name='receipts'),
    path('contacts/', views.contacts, name='contacts'),
    path('todos/', views.todos, name='todos'),
]

start/urls.py
from django.urls.conf import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'start'
urlpatterns = [
    #User ruft den Pfad auf, der im ersten Parameter steht
    #danach wird View im 2.Parameter geladen, die in der Datei Views.py steht
    #Name ist das, was im Browser angezeigt wird unter Pfad
    path('', views.aboutUs, name='aboutUs'), 
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('impressum/', views.impressum, name='impressum'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('emailSend/', views.emailSend, name='emailSend'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('resetPasswordDone/', views.resetPasswordDone, name='resetPasswordDone'),
    path('logout/', views.logout, name='logout'),

    #Passwort zurücksetzen
    #zweiter Übergabewert: Nutzung der Django Funktionen mit eigenen Views zur anzeige (template_name...)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='start/password_reset.html'), name='reset_password'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='start/password_reset_done.html'), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='start/password_reset_confirm.html'), name='password_reset_confirm'),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(template_name='start/password_reset_complete.html'), name='password_reset_complete'),
]

home/models.py
from time import timezone
from django.db import models
import datetime
from django.contrib.auth.models import User
# Create your models here.

#Model für Beleg 
class receipt(models.Model):
    belegnummer = models.IntegerField()
    belegdatum = models.DateField(default=datetime.date.today) #Belegdatum automatisch vorbelegen
    zahlart_choices = [('Bar','Bar'), #verschiedene Zahlarten, beliebig erweiterbar 
                ('Karte','Karte'),]
    zahlart = models.CharField(max_length=10,choices=zahlart_choices,default="Karte")            
    faelligkeit = models.DateField(default=datetime.date.today)
    betrag = models.DecimalField(max_digits=10,decimal_places=2)
    beschreibung = models.CharField(max_length=150)
    konto_name = models.ForeignKey('konto',on_delete=models.CASCADE,to_field='name')#Fremdbeziehung zu Konto
    art_choices = [('Einnahme','Einnahme'),
                ('Ausgabe','Ausgabe'),
                ]
    #user = models.ForeignKey(User,on_delete=models.CASCADE)#Beleg User zuweisen
    art = models.CharField(max_length=20,choices=art_choices,default="Einnahme")#Einnahme oder Ausgabe, 
                                                                                #wichtig für spätere Auswertungen
                                                                                #user = models.ForeignKey(User,on_delete=models.CASCADE)#Beleg User zuweisen
     #user = models.ForeignKey(User,on_delete=models.CASCADE)#Beleg User zuweisen
    #ungetestet, Daten zum User zuordnen

    

class contact(models.Model):
    kontaktnummer = models.IntegerField()
    firma = models.CharField(max_length=25)
    ansprechpartner = models.CharField(max_length=40)
    adresse = models.CharField(max_length=50)
    telefonnummer = models.CharField(max_length=15)
    email = models.EmailField(max_length=254)
    #user = models.ForeignKey(User,on_delete=models.CASCADE)#Beleg User zuweisen
    #user = models.ForeignKey(User,on_delete=models.CASCADE)#Beleg User zuweisen
    #ungetestet, Daten zum User zuordnen

class todo(models.Model):
    nummer = models.IntegerField()
    aufgabe = models.CharField(max_length=30)
    erledigt = models.IntegerField() #erledigt = 1, 'noch nicht erledigt'= 0 
    datum = models.DateField()
    faelligkeit = models.DateField()
    beschreibung = models.CharField(max_length=50)
    #user = models.ForeignKey(User,on_delete=models.CASCADE)#Beleg User zuweisen
    #ungetestet, Daten zum User zuordnen

class konto(models.Model):
    name = models.CharField(max_length=30,primary_key=True)#als Primary Key gesetzt, wird in in Beleg zu Zuordnung verwendet
    bank = models.CharField(max_length=40)
    iban = models.CharField(max_length=22) #IBAN in Deutschland = 22 Stellen 
    bic = models.CharField(max_length=10)
    kontostand = models.DecimalField(max_digits=10,decimal_places=2) # 10-stellige Zahl, für Kleinunternehmer ausreichend
    #user = models.ForeignKey(User,on_delete=models.CASCADE)#Beleg User zuweisen
    #ungetestet, Daten zum User zuordnen

home/forms.py
from django import forms
from django.forms import ModelForm,widgets
from home.models import receipt
from home.models import contact

class ReceiptForm(ModelForm): #Form anhand des Models aufgebaut
    class Meta: 
        model = receipt
        fields = '__all__'

class ContactForm(ModelForm): #Form anhand des Models aufgebaut
    class Meta: 
        model = contact 
        fields = '__all__'      

class AccountDetailForm(): #Form obsolete, Anzeigen der Detaildaten für Konten über Dict-Strukturen gelöst
    summe_einnahmen = forms.DecimalField()
    summe_ausgaben = forms.DecimalField()
    konto = forms.CharField(max_length=30)

class DashboardForm(ModelForm): #Form obsolete, Anzeigen der Daten im Dashboard über Dict-Strukturen gelöst 
    einnahmen = forms.DecimalField()
    ausgaben = forms.DecimalField()
    umsatz = forms.DecimalField()
    kleinugrenze_Umsatz = forms.DecimalField()
    kleinugrenze_Gewinn = forms.DecimalField()
    # def __init__(self,einnahmen,ausgaben,umsatz,kleinugrenze_Umsatz,kleinugrenze_Gewinn):
    #     self.einnahmen = einnahmen
    #     self.ausgaben = ausgaben
    #     self.umsatz = umsatz
    #     self.kleinugrenze_Umsatz = kleinugrenze_Umsatz
    #     self.kleinugrenze_Gewinn = kleinugrenze_Gewinn

home/views.py
from django.shortcuts import render
from django.db.models import Sum
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from home.models import contact, receipt, todo, konto
from home.forms import ReceiptForm
from edit.forms import ReceiptForm as EditReceiptForm
from edit.forms import EditContactForm
from home.forms import ContactForm,AccountDetailForm
from django.contrib.auth.decorators import login_required

# Create your views here.




@login_required()
def dashboard(request):
    all_todos = todo.objects.all()
    all_todos_dict = {
        'todo': all_todos
    }

    context = {"title": "Dashboard","all_todos_dict": all_todos}
    return render(request, 'home/dashboard.html',context)

@login_required()
def profile(request):
    context = {"title": "Profil"}
    return render(request, 'home/profile.html',context)

@login_required()
def accounts(request):
    all_kontos = konto.objects.all()
    all_kontos_dict = {
        'konto': all_kontos
    }
    context = {"title": "Konten","all_kontos_dict":all_kontos}
    return render(request, 'home/accounts.html',context)

@login_required()
def receipts(request):
    if request.method == "POST":
        if 'deleteReceipt' in request.POST:
            receipt.objects.filter(belegnummer=request.POST['belegnummer']).delete()
        elif 'updateReceipt' in request.POST: 
                receipt.objects.filter(belegnummer=request.POST['belegnummer']).update(
                    belegnummer = request.POST['belegnummer'],
                    belegdatum = request.POST['belegdatum'],
                    zahlart = request.POST['zahlart'],
                    faelligkeit = request.POST['faelligkeit'],
                    betrag = request.POST['betrag'],
                    beschreibung = request.POST['beschreibung'],
                    art = request.POST['art'],
                    konto_name = request.POST.get('konto', False))

    all_kontos = konto.objects.all()
    all_kontos_dict = {
        'konto': all_kontos
    }
    all_receipts = receipt.objects.all()
    all_receipts_dict = {
        'receipt': all_receipts
    }
    context = {"title": "Belege","all_receipts_dict": all_receipts,"all_kontos_dict":all_kontos} 
    return render(request, 'home/receipts.html',context)

@login_required()
def contacts(request):
    if request.method == "POST":
        if 'deleteContact' in request.POST:
            contact.objects.filter(kontaktnummer=request.POST['kontaktnummer']).delete()
        elif 'updateContact' in request.POST: 
                contact.objects.filter(kontaktnummer=request.POST['kontaktnummer']).update(
                    kontaktnummer = request.POST['kontaktnummer'],
                    firma = request.POST['firma'],
                    ansprechpartner = request.POST['ansprechpartner'],
                    adresse = request.POST['adresse'],
                    telefonnummer = request.POST['telefonnummer'],
                    email = request.POST['email'])

    all_contacts = contact.objects.all()
    all_contacts_dict = {
        'contact': all_contacts
    }
    context = {"title": "Kontakte","all_contacts_dict": all_contacts,"all_contacts_dict": all_contacts}
    return render(request, 'home/contacts.html',context)

@login_required()
def todos(request):
    all_todos = todo.objects.all()
    all_todos_dict = {
        'todo': all_todos
    }
    context = {"title": "To-Dos","all_todos_dict": all_todos}
    return render(request, 'home/todos.html',context)

@login_required()
def accountDetails(request):
    context = {"title": "Konten"}
    
    all_einnahmen = receipt.objects.filter(konto_name='Personalausgaben',art='Einnahme')
    all_einnahmen_dict = {
        'einnahme': all_einnahmen
    }
    summe_e = receipt.objects.filter(konto_name='Personalausgaben',art='Einnahme').aggregate(sum=Sum('betrag'))['sum']
    print(summe_e)
    
    all_ausgaben = receipt.objects.filter(konto_name = 'Personalausgaben',art='Ausgabe')
    all_ausgaben_dict = {
        'receipt': all_ausgaben
    }
    summe_a = receipt.objects.filter(konto_name='Personalausgaben',art='Ausgabe').aggregate(sum=Sum('betrag'))['sum']
    name = 'Personalausgaben'

    
    context = {"title": "Details","all_ausgaben_dict": all_ausgaben,"all_einnahmen_dict":all_einnahmen,"konto":name,
        "summe_einnahmen":summe_e,"summe_ausgaben":summe_a}
    return render(request, 'home/accountDetails.html',context)

home/templates/home/accountDetails.html
{% extends "home/base.html"%}
{%load static%}


{% block hauptinhalt %}
<div class="col py-3">
   <div class="row">
      <h1>Details für Konto {{konto}}</h1>
      <p></p>
      <div class="col-sm-4">
         <div class="card">
            <div class="card-body">
               <h5 class="card-title">Einnahmen</h5>
               <p class="card-text">Summe der Einnahmen: {{summe_einnahmen}} €</p>
            </div>
         </div>
      </div>
   </div>
   <p></p>
   <div class="table-responsive">
      <table class="table table-bordered table-hover table-striped">
         <thead>
            <tr>
               <th>Belegnummer</th>
               <th>Belegdatum</th>
               <th>Zahlart</th>
               <th>Fälligkeit</th>
               <th>Betrag</th>
               <th>Beschreibung</th>
            </tr>
         </thead>
         {% if all_einnahmen_dict %}
         <tbody>
            {% for einnahme in all_einnahmen_dict %}
            <tr>
               <td>{{einnahme.belegnummer}}</td>
               <td>{{einnahme.belegdatum}}</td>
               <td>{{einnahme.zahlart}}</td>
               <td>{{einnahme.faelligkeit}}</td>
               <td>{{einnahme.betrag}} €</td>
               <td>{{einnahme.beschreibung}}</td>
            </tr>
            {% endfor %}

         </tbody>
         {% endif %}
      </table>
   </div>
   <p></p>
   <div class="col-sm-4">
      <div class="card">
         <div class="card-body">
            <h5 class="card-title">Ausgaben</h5>
            <p class="card-text">Summe der Ausgaben: {{summe_ausgaben}} €</p>
         </div>
      </div>
   </div>

   <div class="table-responsive">
      <table class="table table-bordered table-hover table-striped">
         <thead>
            <tr>
               <th>Belegnummer</th>
               <th>Belegdatum</th>
               <th>Zahlart</th>
               <th>Fälligkeit</th>
               <th>Betrag</th>
               <th>Beschreibung</th>
            </tr>
         </thead>
         {% if all_ausgaben_dict %}
         <tbody>
            {% for ausgabe in all_ausgaben_dict %}
            <tr>
               <td>{{ausgabe.belegnummer}}</td>
               <td>{{ausgabe.belegdatum}}</td>
               <td>{{ausgabe.zahlart}}</td>
               <td>{{ausgabe.faelligkeit}}</td>
               <td>{{ausgabe.betrag}} €</td>
               <td>{{ausgabe.beschreibung}}</td>
            </tr>
            {% endfor %}
         </tbody>
         {% endif %}
      </table>
   </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
   integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
   integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
   integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
   integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
   crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
   integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
   integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock hauptinhalt %}

home/templates/home/accounts.html
{% extends "home/base.html"%}
{%load static%}

<!--Die Konten werden als Bootstrap-Cards, also als Rechtecke angezeigt. Wieder wird eine For-Schleife verwendet, um aus der Konten-Liste die Konten anzuzeigen. -->
{% block hauptinhalt %}
<div class="col mt-3 mb-3">
  <div class="row">
    <div class="col-12 ">
      <div class="card bg-light p-3 text-center">
        <h1 class="text-center mb-5">Konten</h1>
        <div class="row mb-3">
          <div class="col-sm-6">
            <div class="card text-white bg-success">
              <div class="card-body">

                <h5 class="card-title">Einnahmen</h5>
                <p class="card-text">27351 €</p>
                <!--Bei den A-Tags wird jeweils die Account-Details Seite als Link angegeben.. -->
                <h5 class="card-title">Einnahmen</h5>
                <p class="card-text">27351 €</p>
                <!--Bei den A-Tags wird jeweils die Account-Details Seite als Link angegeben.. -->
                <a href="{% url 'home:accountDetails'%}" class="btn btn-light">Details</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card text-white bg-danger ">
              <div class="card-body">
                <h5 class="card-title">Ausgaben</h5>
                <p class="card-text">17351 €</p>
                <a href="{% url 'home:accountDetails'%}" class="btn btn-light">Details</a>
              </div>
            </div>
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-sm-6">
            <div class="card text-white bg-secondary">
              <div class="card-body">
                <h5 class="card-title">Portokasse</h5>
                <p class="card-text">2425 €</p>
                <a href="{% url 'home:accountDetails'%}" class="btn btn-light">Details</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card text-white bg-secondary ">
              <div class="card-body">
                <h5 class="card-title">Personal</h5>
                <p class="card-text">125850 €</p>
                <a href="{% url 'home:accountDetails'%}" class="btn btn-light">Details</a>
              </div>
            </div>
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-sm-6">
            <div class="card text-white bg-secondary">
              <div class="card-body">
                <h5 class="card-title">Büromaterial</h5>
                <p class="card-text">3351 €</p>
                <a href="{% url 'home:accountDetails'%}" class="btn btn-light">Details</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card text-white bg-secondary ">
              <div class="card-body">
                <h5 class="card-title">Fuhrpark</h5>
                <p class="card-text">11351 €</p>
                <a href="{% url 'home:accountDetails'%}" class="btn btn-light">Details</a>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          {% if all_kontos_dict %}
          {% for konto in all_kontos_dict %}
          <div class="col-sm-6 mb-3">
            <div class="card text-white bg-secondary">
              <div class="card-body">
                <h5 class="card-title">{{konto.name}}</h5>
                <p class="card-text">Kontostand: {{konto.kontostand}} €</p>
                <a href="{% url 'home:accountDetails' %}" class="btn btn-light">Details</a>
              </div>
            </div>
          </div>
          {%endfor%}
          {%endif%}
          <div class="col-sm-2">
            <div class="card text-white bg-dark">
              <div class="card-body">
                <h5 class="card-title">Neues Konto erstellen</h5>
                <a href="{% url 'edit:editBankAccount'%}" class="btn btn-light">+</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
  integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
  integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
  integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock hauptinhalt %}

home/templates/home/navbar.html
<!--Main Navigation-->
{%load static%}

{% block hauptinhalt %}
<!--Navigation Bar-->
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home:dashboard'%}">EasyAccounting</a>
    <ul class="navbar-nav ml-auto">
        <div class="dropdown"> <a href="#"
                class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1"
                data-bs-toggle="dropdown" aria-expanded="false"> <img
                    src="https://avatars.githubusercontent.com/u/3?v=3" alt="" width="32" height="32"
                    class="rounded-circle me-2"> <strong> Unternehmen </strong> </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" id="settings" href="{% url 'edit:settings'%}">Einstellungen</a></li>
                <li><a class="dropdown-item" href="{% url 'home:profile'%}">Profil</a></li>
                <li>
                    <form action="{% url 'start:logout' %}" method="post">
                        {% csrf_token %}
                <li><button type="submit" value="Abmelden" class="dropdown-item">Abmelden</button></li>
                </form>
            </ul>
        </div>
    </ul>
</nav>

<!--Sidebar-->
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Navigation</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="{% url 'home:dashboard'%}" class="nav-link align-middle px-0 text-white">
                            <i class="fa fa-tachometer-alt"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'home:accounts'%}" class="nav-link px-0 align-middle text-white">
                            <i class="fa fa-arrow-down"></i> <span class="ms-1 d-none d-sm-inline">Konten</span> </a>
                    </li>

                    <li>
                        <a href="{% url 'home:receipts'%}" class="nav-link px-0 align-middle text-white">
                            <i class="fa fa-bookmark"></i> <span class="ms-1 d-none d-sm-inline">Belege</span></a>
                    </li>
                    
                    <li>
                        <a href="{% url 'home:contacts'%}" class="nav-link px-0 align-middle text-white">
                            <i class="fa fa-id-card"></i> <span class="ms-1 d-none d-sm-inline">Kontakte</span></a>
                    </li>

                    <li>
                        <!-- Verweis zum runterscrollen auf Seite
                        <a href="http://127.0.0.1:8000/dashboard/#todo" class="nav-link px-0 align-middle text-white">
                    -->
                        <a href="{% url 'home:todos'%}" class="nav-link px-0 align-middle text-white">
                            <i class="fa fa-clipboard-list"></i> <span
                                class="ms-1 d-none d-sm-inline">To-Do's</span></a>
                    </li>
                    
                    <li>
                        <li>
                            <a href="mailto:'easy.accmanager@gmail.com'" class="nav-link px-0 align-middle text-white">
                                <i class="fa fa-question"></i> <span class="ms-1 d-none d-sm-inline">Support</span></a>
                        </li>
                    </li>
          
                </ul>
            </div>
        </div>
        {% endblock hauptinhalt %}