Wahlprojekt/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from start import views

from django.contrib.auth import views as auth_views
#Sammlung der Urls aus unseren erstellten Apps
urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Alle urls aus unserer App start werden eingebunden
    path('', include('start.urls')),
    path('', include('home.urls')),
    path('', include('edit.urls')),
    
    #Passwort vergessen
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='start/password_reset.html'), name='reset_password'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='start/password_reset_done.html'), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='start/password_reset_confirm.html'), name='password_reset_confirm'),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(template_name='start/password_reset_complete.html'), name='password_reset_complete'),
]

edit/urls.py
from django.urls.conf import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'edit'
urlpatterns = [
    #User ruft den Pfad auf, der im ersten Parameter steht
    #danach wird View im 2.Parameter geladen, die in der Datei Views.py steht
    #Die Index View gibt unsere main.html Datei zurück
    #Name ist das, was im Browser angezeigt wird unter Pfad
    path('setttings/', views.settings, name='settings'),
    path('editBankData/', views.editBankData, name='editBankData'),
    path('deleteAccount/', views.deleteAccount, name='deleteAccount'),
    path('editReceipts/', views.editReceipts, name='editReceipts'),
    path('editContacts/', views.editContacts, name='editContacts'),
    path('editBankAccount/', views.editBankAccount, name='editBankAccount'),
    path('editToDos/', views.editToDos, name='editToDos'),
    path('change_password_form', auth_views.PasswordChangeView.as_view(template_name='edit/change_password_form.html', success_url=reverse_lazy('edit:password_change_done')), name='change_password_form'),
    path('password_change_done', auth_views.PasswordChangeDoneView.as_view(template_name='edit/change_password_done.html'), name='password_change_done'),
]

start/urls.py
from django.urls.conf import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'start'
urlpatterns = [
    #User ruft den Pfad auf, der im ersten Parameter steht
    #danach wird View im 2.Parameter geladen, die in der Datei Views.py steht
    #Name ist das, was im Browser angezeigt wird unter Pfad
    path('', views.aboutUs, name='aboutUs'), 
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('impressum/', views.impressum, name='impressum'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('emailSend/', views.emailSend, name='emailSend'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('resetPasswordDone/', views.resetPasswordDone, name='resetPasswordDone'),
    path('logout/', views.logout, name='logout'),

    #Passwort zurücksetzen
    #zweiter Übergabewert: Nutzung der Django Funktionen mit eigenen Views zur anzeige (template_name...)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='start/password_reset.html'), name='reset_password'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='start/password_reset_done.html'), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='start/password_reset_confirm.html'), name='password_reset_confirm'),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(template_name='start/password_reset_complete.html'), name='password_reset_complete'),
]

start/forms.py
from django import forms

#Form, mit den Daten, die der User zum Anmelden braucht.
class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    vorname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    nachname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    passwort = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    passwort_wiederholen = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

start/views.py
# Create your views here.
from django.shortcuts import redirect, render
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from .forms import RegisterForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as logouts
from django.contrib.auth.decorators import login_required

#Methoden, die in Urls.py aufgerufen werden. Diese geben eine Html Datei und den dazugehörigen Titel zurück
def aboutUs(request):
    context = {"title": "Über uns"}
    return render(request, 'start/aboutUs.html',context)

def impressum(request):
    context = {"title": "Impressum"}
    return render(request, 'start/impressum.html',context)

def register(request):
    #Wenn es sich um eine POST-Anfrage handelt, müssen wir die Formulardaten verarbeiten
    template = 'start/register.html'
   
    if request.method == 'POST':
        # Formularinstanz erstellen und mit Daten der Anfrage füllen
        form = RegisterForm(request.POST)
        # Prüfen, ob es gültig ist
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Benutzername existiert bereits.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email-Adresse existiert bereits.'
                })
            elif form.cleaned_data['passwort'] != form.cleaned_data['passwort_wiederholen']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwörter stimmen nicht überein.'
                })
            else:
                # User erstellen
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['passwort']
                )
                
                user.first_name = form.cleaned_data['vorname']
                user.last_name = form.cleaned_data['nachname']
                user.save()
                
                #ungetestet, nicht umgesetzt
                #Standardkonten für User anlegen, z.B. 
                #Büromaterial, Fuhrpark, Miete, Personal, Portokasse, Einnahmen, Dienstleistungen, Lizenzen, Spenden, Gewinn

                # User einloggen
                login(request, user)
               
                # Redirect zur Login Seite
                return render(request, 'start/login.html')

   #Keine POST Daten vorhanden, nur die Seite anzeigen.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})

def user_login(request):
    if request.method == 'POST':
        # Anfrage bearbeiten, wenn Daten vorhanden
        username = request.POST['username']
        password = request.POST['password']
        # Überprüfen ob Username und Passwort korrekt sind
        user = authenticate(username=username, password=password)
        if user is not None:
            #Session Cookie speichern, damit man sich anmelden kann
            login(request, user)
            #User anmmelden
            return render(request, 'home/dashboard.html')
        else:
            #Falsche Eingaben, Error anzeigen
            return render(request, 'start/login.html', {'error_message': 'Falscher Username oder Passwort.'})
    else:
        #Keine POST Daten vorhanden, nur die Seite anzeigen.
        return render(request, 'start/login.html')

def logout(request):
    if request.method == 'POST':
        logouts(request)
        return render(request, 'start/login.html/')

def forgotPassword(request):
    context = {"title": "Passwort vergessen"}
    return render(request, 'start/forgotPassword.html',context)

def reset_password(request):
    context = {"title": "Passwort zurücksetzen"}
    return render(request, 'start/password_reset.html',context)

def password_reset_done(request):
    context = {"title": "Passwort zurücksetzen"}
    return render(request, 'start/password_reset_done.html',context)

@login_required()
def emailSend(request):
    context = {"title": "Passwort zurücksetzen"}
    return render(request, 'start/emailSend.html',context)

@login_required()
def resetPassword(request):
    context = {"title": "Neues Passwort festlegen"}
    return render(request, 'start/resetPassword.html',context)

@login_required()
def resetPasswordDone(request):
    context = {"title": "Passwort geändert"}
    return render(request, 'start/resetPasswordDone.html',context)

start/templates/start/aboutUs.html
{% extends "start/base.html"%}
{%load static%}

{% block hauptinhalt %}

<div class="container px-5 py-5" style="background-color: #212529; color: white;">
  <div class="row text-center mt-5 mb-4">
    <div class="col-12">
      <h1 class="mb-3">Willkommen bei EasyAccounting!</h1>
      <p style="font-size: 23px;">Unser Produkt unterstützt Sie und Ihr Unternehmen bei der einfachen Buchhaltung. </br>
      Wir helfen Ihnen, das Wichtigste im Blick zu behalten:</br>
      Ihr Unternehmen und Ihre Ziele.
      </p>
    </div>
  </div>
  <div class="row text-center mb-4">
    <div class="col"><img src="https://bootstrapious.com/i/snippets/sn-about/img-1.jpg" alt=""
        class="img-fluid mb-4 mb-lg-0" style="height: 270px;">
    </div>
  </div>
  <div class="row text-center mb-4">
    <div class="col-12">
      <h1 class="mb-3">Alles im Überblick</h1>
        <p class="mb-4" style="font-size: 23px;">Mit EasyAccounting können Sie Konten anlegen, Belege hinzufügen, Kontakte pflegen und vieles mehr. </p>
        <a href="{% url 'start:register'%}" class="btn btn-light px-5 rounded-pill shadow-sm mb-4">Jetzt ausprobieren!</a>
    </div>
  </div>
  <div class="row text-center">
    <h1 class="mb-3">Unser Team</h2>
      <p></p>
      <div class="col-xl-3 col-sm-6">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img
            src="https://bootstrapious.com/i/snippets/sn-about/avatar-3.png" alt="" width="100"
            class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0" style="color: black;">Serhat Bingöl</h5><span class="small text-uppercase"
            style="color: black;">Projektmanager</span>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img
            src="https://bootstrapious.com/i/snippets/sn-about/avatar-1.png" alt="" width="100"
            class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0" style="color: black;">Fatih Dülgerog</h5><span class="small text-uppercase"
            style="color: black;">Architekt/Designer</span>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img
            src="https://bootstrapious.com/i/snippets/sn-about/avatar-3.png" alt="" width="100"
            class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0" style="color: black;">Fevzi Gencer</h5><span class="small text-uppercase"
            style="color: black;">Entwicklung (Front-End)</span>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img
            src="https://bootstrapious.com/i/snippets/sn-about/avatar-1.png" alt="" width="100"
            class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0" style="color: black;">Julian Schnäbele</h5><span class="small text-uppercase"
            style="color: black;">Entwicklung (Back-End)</span>
        </div>
      </div>
  </div>
</div>
{% endblock hauptinhalt %}

start/templates/start/base.html
<!--Basis Template für die App Start-->
{%load static%}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="de">

<head>
    <title> {{title}} </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS Bootstrap Einbindung -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--Eigene Css Anweisungen-->
    <style>
        .navbar {
            overflow: hidden;
            position: fixed; /*Navbar fixiert*/
            top: 0; /* Navbar ganz oben */
            width: 100%; /* Volle breite */
            padding-left: 15px;
            padding-right: 15px;
        }

        /*Links in Navbar werden rechts angezeigt*/
        .navbar-nav {
            margin-left: auto;
            padding: 10px;
        }

        /*Wenn etwas mittig dargestellt werden soll*/
        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        /*Abstände, Farben usw. vom Login View*/
        .loginWindow {
            margin-top: 100px;
            border: 5px solid black;
            background-color: #ddd;
            padding: 15px;
        }

        /*Abstände, Farben usw. vom Register View*/
        .registerWindow {
            margin-top: 100px;
            border: 5px solid black;
            background-color: #ddd;
            padding: 20px;
        }

        /*Abstände, Rahmen, Größe von Passwort vergessen */
        .forgotPassword {
            margin-top: 200px;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: 100px;
            border: 5px solid black;
            background-color: #ddd;
            padding: 30px;
            width: 400px;
            height: 280px;
        }
        
        /*Hintergrundbild auf der gesamten App Start*/
        #bild {
            background: url("{% static 'img/main.jpeg' %}") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        .asteriskField {
            display: none;
        }
    </style>

</head>

<body id="bild"> <!--Einbindung des Hintergrundbilds im Body-->
    {%include "start/navbar.html"%} <!--Navigationbar auf diese Weise in jeder View, weil alle Views von base.html erben-->
    
    {% block hauptinhalt %} <!--Template System-->
    {% endblock hauptinhalt %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
</body>

</html>

start/templates/start/impressum.html
{% extends "start/base.html"%}
{%load static%}

{% block hauptinhalt %}
<div class="container px-5 py-5" style="background-color: #212529; color: white;">
    <div class="row mt-5 mb-4">
        <div class='impressum'>
            <h1>Impressum</h1>
            <p>Angaben gemäß § 5 TMG</p>
            <p> Projekt des Moduls Wahlprojekt, Hochschule RheinMain<br>
                Unter den Eichen 5<br>
                65195 Wiesbaden <br>
            </p>
            <p> <strong>Vertreten durch: </strong><br>
                Serhat Bingöl<br>
                Fevzi Gencer<br>
                Fatih Dülgerog<br>
                Julian Schnäbele
            </p>
            <p><strong>Kontakt:</strong> <br>
                E-Mail: <a href='mailto:easy.accmanager@gmail.com'>easy.accmanager@gmail.com</a></br></p>
        
            <p><strong>Haftungsausschluss: </strong> <br><br>
                <strong>Urheberrecht</strong><br><br>
                Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen
                Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der
                Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.
                Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.
                Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte
                Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem
                auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei
                Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend
                entfernen.<br><br><strong>Datenschutz</strong><br><br>
                Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf
                unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben
                werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre
                ausdrückliche Zustimmung nicht an Dritte weitergegeben. <br>
                Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail)
                Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist
                nicht möglich. <br>
                Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur
                Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit
                ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im
                Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.<br>
            </p>
        </div>
    </div>
</div>
{% endblock hauptinhalt %}

start/templates/start/login.html
{% extends "start/base.html"%}
{%load static%}

{% block hauptinhalt %}
<div class="container-fluid py-5 mt-5">
  <div class="row mt-lg-5 justify-content-center align-items-center">
    <div class="col-12 col-md-8 col-sm-5 col-xl-4">
      <div class="card-body text-center">
        <center>
        <form class="loginWindow" action="{% url 'start:user_login' %}" method="post">
          {% csrf_token %}
          <h1 class="mb-4">Login</h1>
          <div class="form-outline mb-4">
            <label class="form-label fw-bold mb-3">Email Adresse</label>
            <input name="username" type="text" class="form-control form-control-lg w-75" placeholder="test@unternehmen.de">
          </div>
          <div class="form-outline mb-4">
            <label class="form-label fw-bold mb-3">Passwort</label>
            <input name="password" type="password" class="form-control form-control-lg w-75" placeholder="********">
          </div>
          {% if error_message %}
          <p class="bg-danger p-d ml-b">{{ error_message }}</p>
          {% endif %}
          <p></p>
          <input name="login" type="submit" value="Login" class="btn btn-dark" />
          <p></p>
          <a href="{% url 'start:reset_password'%}">Passwort vergessen?</a>
          <p></p>
          Noch kein Konto? 
          <a href="{% url 'start:register'%}">Hier registieren</a>
        </form>
      </center>
      </div>
    </div>
  </div>
</div>
{% endblock hauptinhalt %}

start/templates/start/navbar.html
{%load static%}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">

  <a class="navbar-brand" href="{% url 'start:aboutUs'%}"> EasyAccounting</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar7">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse justify-content-stretch" id="navbar7">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'start:user_login'%}">LOGIN</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'start:register'%}">REGISTRIEREN</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'start:aboutUs'%}">ÜBER UNS</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'start:impressum'%}">IMPRESSUM</a>
      </li>
    </ul>
  </div>
</nav>

start/templates/start/password_reset.html
{% extends "start/base.html"%}
{%load static%}
{% load crispy_forms_tags %}
{% block hauptinhalt %}
<div class="container-fluid py-5 mt-5">
  <div class="row mt-lg-5 justify-content-center align-items-center">
    <div class="col-12 col-md-8 col-sm-5 col-xl-4">
      <div class="card-body text-center">
        <form class="loginWindow" method="post">
          {% csrf_token %}
          <h3 class="mb-4">Passwort vergessen?</h3>
          <div class="form-outline mb-4">
            Geben Sie Ihre E-Mail Adresse ein, um Ihr Passwort zurückzusetzen.
          </div>
          <div class="form-outline mb-2">
            {{ form|crispy }}
          </div>
          <button type="submit" class="btn btn-dark">Zurücksetzen</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock hauptinhalt %}

start/templates/start/password_reset_complete.html
{% extends "start/base.html"%}
{%load static%}

{% block hauptinhalt %}
  <center>
    Dein Passwort wurde erfolgreich zurückgesetzt <br/>
    Bitte kehren Sie zum Login zurück und melden Sie sich an.
    
    <div class="forgotPassword">

      <div class="col-9 shadow-none p-1 mb-2t rounded">
      </div>
      Dein Passwort wurde erfolgreich zurückgesetzt <br/>
      Bitte kehren Sie zum Login zurück und melden Sie sich an
    </div>
  
  </center>
{% endblock hauptinhalt %}

start/templates/start/password_reset_confirm.html
{% extends "start/base.html"%}
{%load static%}
{% load crispy_forms_tags %}

{% block hauptinhalt %}
  <center>
    <div class="loginWindow">
      <h2>Passwort zurücksetzen</h2>
      Lege hier dein neues Passwort fest.
      <form method="post"> 
        {%csrf_token%}
        {{ form|crispy }}
        <button type="submit"> Reset </button>


      </form>
    </div> 
  </center>
{% endblock hauptinhalt %}

start/templates/start/password_reset_done.html
{% extends "start/base.html"%}
{%load static%}

{% block hauptinhalt %}
<center>
  <div class="forgotPassword">

    <div class="col-9 shadow-none p-1 mb-2t rounded">
      <h3> Email gesendet!</h3>
    </div>
      Wir haben dir eine E-Mail zum Zurücksetzen deines Passworts geschickt! </br>
      Bitte check deinen Postfach!
  </div>
</center>
{% endblock hauptinhalt %}

start/templates/start/register.html
{% extends "start/base.html"%} <!--Einbindung der base.html Datei-->
{%load static%} <!--Einbindung der statischen Dateien (Hintergrundbild)-->
{% load crispy_forms_tags %} 
{% block hauptinhalt %}
<div class="container-fluid py-5 mt-5">
  <div class="row mt-lg-5 justify-content-center align-items-center">
    <div class="col-12 col-md-8 col-sm-5 col-xl-4">
      <div class="card-body text-center">
        <center>
          <form class="registerWindow" action="{% url 'start:register' %}" method="post">
            {% csrf_token %}
            <h1 class="mb-4">Registrieren</h1>

            <div class="row mx-2">
              {% if error_message %}
              <p class="bg-danger p-d ml-b">{{ error_message }}</p>
              {% endif %}
              
              <div class="col-6 mb-4">
                <div class="form-group">
                  <!--Crips Field sorgt dafür, dass die Textfelder ordentlich und im Bootstrap Stil aussehen. -->
                  {{ form.vorname|as_crispy_field }}
                </div>
              </div>
              <div class="col-6 mb-4">
                <div class="form-group">
                  {{ form.nachname|as_crispy_field }}
                </div>
              </div>
            </div>

            <div class="row mx-2">
              <div class="col-6 mb-4">
                <div class="form-group">
                  {{ form.email|as_crispy_field }}
                </div>
              </div>
              <div class="col-6 mb-4">
                <div class="form-group">
                  {{ form.username|as_crispy_field }}
                </div>
              </div>
            </div>

            <div class="row mx-2">
              <div class="col-6 mb-4">
                <div class="form-group">
                  {{ form.passwort|as_crispy_field }}
                </div>
              </div>
              <div class="col-6 mb-4">
                <div class="form-group">
                  {{ form.passwort_wiederholen|as_crispy_field }}
                </div>
              </div>
            </div>
            <div class="col-6">
              <input name="register" type="submit" value="Konto erstellen" class="btn btn-dark" />
            </div>
          </form>
        </center>
      </div>
    </div>
  </div>
</div>
{% endblock hauptinhalt %}

start/templates/start/resetPassword.html
{% extends "start/base.html"%}
{%load static%}

{% block hauptinhalt %}
  <center>
    <div class="loginWindow">
      <h2>Passwort zurücksetzen</h2>
      Lege hier dein neues Passwort fest.
        <form>
          <div class="col-9 shadow-none p-1 mb-2t rounded">
            <label class="form-label">Neues Passwort</label>
            <input type="email" class="form-control" placeholder="********">
          </div>
       
          <div class="col-9 shadow-none p-1 mb-2  rounded">
            <label class="form-label">Passwort wiederholen</label>
            <input type="password" class="form-control" placeholder="********">
          </div class="col-3">
          
          <p></p>
          <a type="text" class="btn btn-dark" href="{% url 'start:resetPasswordDone'%}">Passwort zurücksetzen</a>
        </form>
    </div> 
  </center>
{% endblock hauptinhalt %}

start/templates/start/resetPasswordDone.html
{% extends "start/base.html"%}
{%load static%}

{% block hauptinhalt %}
  <center>
    <div class="forgotPassword">
      <h3>Passwort zurückgesetzt!</h3>
      
      <p></p>
      Dein Passwort wurde erfolgreich zurückgesetzt <br/>
      Bitte kehren Sie zum Login zurück und melden Sie sich an.
      <p></p>
      
      <a type="text" class="btn btn-dark" href="{% url 'start:login'%}">Zurück zum Login</a>
    </div>
 
  </center>
{% endblock hauptinhalt %}