Wahlprojekt/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from start import views

from django.contrib.auth import views as auth_views
#Sammlung der Urls aus unseren erstellten Apps
urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Alle urls aus unserer App start werden eingebunden
    path('', include('start.urls')),
    path('', include('home.urls')),
    path('', include('edit.urls')),
    
    #Passwort vergessen
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='start/password_reset.html'), name='reset_password'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='start/password_reset_done.html'), name='password_reset_done'),
    path("password_reset_confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='start/password_reset_confirm.html'), name='password_reset_confirm'),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(template_name='start/password_reset_complete.html'), name='password_reset_complete'),
]

edit/urls.py
from django.urls.conf import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'edit'
urlpatterns = [
    #User ruft den Pfad auf, der im ersten Parameter steht
    #danach wird View im 2.Parameter geladen, die in der Datei Views.py steht
    #Die Index View gibt unsere main.html Datei zurück
    #Name ist das, was im Browser angezeigt wird unter Pfad
    path('setttings/', views.settings, name='settings'),
    path('editBankData/', views.editBankData, name='editBankData'),
    path('deleteAccount/', views.deleteAccount, name='deleteAccount'),
    path('editReceipts/', views.editReceipts, name='editReceipts'),
    path('editContacts/', views.editContacts, name='editContacts'),
    path('editBankAccount/', views.editBankAccount, name='editBankAccount'),
    path('editToDos/', views.editToDos, name='editToDos'),
    path('change_password_form', auth_views.PasswordChangeView.as_view(template_name='edit/change_password_form.html', success_url=reverse_lazy('edit:password_change_done')), name='change_password_form'),
    path('password_change_done', auth_views.PasswordChangeDoneView.as_view(template_name='edit/change_password_done.html'), name='password_change_done'),
]

home/urls.py
from django.urls.conf import path
from . import views

app_name = 'home'
urlpatterns = [
    #User ruft den Pfad auf, der im ersten Parameter steht
    #danach wird View im 2.Parameter geladen, die in der Datei Views.py steht
    #Die Index View gibt unsere main.html Datei zurück
    #Name ist das, was im Browser angezeigt wird unter Pfad
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('accounts/', views.accounts, name='accounts'),
    path('accountDetails/', views.accountDetails, name='accountDetails'),
    path('receipts/', views.receipts, name='receipts'),
    path('contacts/', views.contacts, name='contacts'),
    path('todos/', views.todos, name='todos'),
]

edit/models.py
from django.db import models

# Create your models here.
# class receipt(models.Model):
#     belegnummer = models.IntegerField()
#     belegdatum = models.DateField()
#     zahlart_choices = [('Bar','Bar'),
#                 ('Karte','Karte'),]
#     zahlart = models.CharField(max_length=10,choices=zahlart_choices,default="K")
#     faelligkeit = models.DateField()
#     betrag = models.DecimalField(max_digits=10,decimal_places=2)
#     #datei = models.FileField()
#     beschreibung = models.CharField(max_length=150)

edit/forms.py
from django.forms import ModelForm, widgets
import datetime
from django.forms.models import ModelChoiceField
from home.models import contact, receipt, konto, todo

from home.models import contact, receipt
from django import forms

class ReceiptForm(ModelForm):
    class Meta: 
        model = receipt
        fields = '__all__'
        widgets = {
            'belegdatum' : widgets.DateInput(attrs={'type': 'date'}),
            'faelligkeit' : widgets.DateInput(attrs={'type': 'date'})
        }

class EditContactForm(ModelForm):
    class Meta: 
        model = contact
        fields = '__all__'
        
class EditAccountForm(ModelForm):
    class Meta:
        model = konto
        fields = '__all__'

class EditTodoForm(ModelForm):
    class Meta: 
        model = todo
        fields = '__all__'
        widgets = {
            'datum' : widgets.DateInput(attrs={'type': 'date'}),
            'faelligkeit' : widgets.DateInput(attrs={'type': 'date'})
        }
    

edit/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from edit.forms import ReceiptForm
from edit.forms import EditContactForm, EditAccountForm, EditTodoForm
from home.models import contact, konto, receipt, todo
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

# login_required ist dafür da, dass die Seite nur aufgerufen werden kann, wenn man angemeldet ist
@login_required()
def settings(request):
    context = {"title": "Einstellungen"}
    return render(request, 'edit/settings.html',context)

@login_required()
def editBankData(request):
    context = {"title": "Bankdaten"}
    return render(request, 'edit/editBankData.html',context)

@login_required()
def deleteAccount(request):
    context = {"title": "Account löschen"}
    return render(request, 'edit/deleteAccount.html',context)

@login_required()
def editReceipts(request):
    if request.method == 'POST': 
        form = ReceiptForm(request.POST)
        if form.is_valid():
            if receipt.objects.filter(belegnummer=form.cleaned_data['belegnummer']).exists():
                messages.error(request,'Beleg unter dieser Nummer existiert bereits.')
                return redirect('edit:editReceipts') #Wenn Belegnummer bereits existiert, Fehlermeldung anzeigen
            try:
                form.save()
            except:
                messages.error(request,'Beleg konnte nicht gesichert werden!')
                return redirect('edit:editReceipts') #Wenn Beleg anderweitig nicht gesichert werden konnte, Fehlermeldung anzeigen
            messages.success(request,'Beleg erfolgreich gesichert!')
            return redirect('edit:editReceipts')

    else:   
        letzter_beleg = receipt.objects.last() #letzten Beleg holen 
        letzte_belegnummer = letzter_beleg.belegnummer + 1 #Auf Nummer des Belegs 1 addieren, für 'automatische' Vergabe der Belegnummer 
        form = ReceiptForm(initial={'belegnummer': letzte_belegnummer}) #neue Belegnummer zuweisen 
    context = {"title": "Beleg hinzufügen","form": form}
    return render(request, 'edit/editReceipts.html',context)

@login_required()
def editContacts(request):
    if request.method == 'POST':
        form = EditContactForm(request.POST)
        if form.is_valid():
            if contact.objects.filter(kontaktnummer=form.cleaned_data['kontaktnummer']).exists():
                form = EditContactForm()
                messages.error(request,'Kontakt unter dieser Nummer existiert bereits.')
                return redirect('edit:editContacts') #Fehler, wenn Kontakt bereits existiert 
            form.save()
            messages.success(request,'Kontakt erfolgreich hinzugefügt!') #Erfolgsnachricht, wenn Kontakt gespeichert 
            return redirect('edit:editContacts')
    else: 
        form = EditContactForm()
    context = {"title": "Kontakte bearbeiten","form":form}
    return render(request, 'edit/editContacts.html',context)

@login_required()
def editBankAccount(request):
    if request.method == 'POST':
        form = EditAccountForm(request.POST)
        if form.is_valid():
            if konto.objects.filter(name=form.cleaned_data['name']).exists():
                form = EditAccountForm()
                messages.error(request,'Konto mit diesem Namen existiert bereits.')
                return redirect('edit:editBankAccount') #Fehlermeldung, Konto existiert bereits 
            try:
                form.save()
            except:
                messages.error(request,'Konto konnte nicht gesichert werden!') #Fehlermeldung, Konto konnte aus anderem Grund nicht gesichert werden
                return redirect('edit:editBankAccount')
            messages.success(request,'Konto erfolgreich gesichert!')
            return redirect('edit:editBankAccount')
    else: 
        form = EditAccountForm()
    context = {"title": "Konto erstellen","form":form}
    return render(request, 'edit/editBankAccount.html',context)
    
@login_required()
def editToDos(request):
    if request.method == 'POST':
        postdata = request.POST #postdata entspricht jetzt Daten aus request.POST
        postdata._mutable = True #mutable -> Daten könnnen verändert werden
        postdata['erledigt'] = '0' #erledigt auf 0 setzen, da kein Status erledigt im Frontend vorhanden 
        postdata._mutable = False 
        form = EditTodoForm(postdata) #EditTodoForm mit 'geänderten' Daten aus postdata instanziieren 
        if form.is_valid():
            if todo.objects.filter(nummer=form.cleaned_data['nummer']).exists():
                form = EditTodoForm()
                messages.error(request,'To-Do mit dieser Nummer existiert bereits.')
                return redirect('edit:editToDos') #Fehlermeldung, To-Do existiert bereits 
            try:
                form.save()
            except:
                messages.error(request,'To-Do konnte nicht gesichert werden!')
                return redirect('edit:editToDos')
            messages.success(request,'To-Do erfolgreich gesichert!')
            return redirect('edit:editToDos')
    else: 
        form = EditTodoForm()
    context = {"title": "Aufgabe erstellen","form":form}
    return render(request, 'edit/editToDos.html',context)


@login_required()
def password_change_done(request):
    context = {"title": "Aufgabe erstellen"}
    return render(request, 'edit/change_password_done.html',context)

edit/templates/edit/change_password_done.html
{% extends "edit/base.html" %}

{% block hauptinhalt %}
<div class="col mt-5 py-5 text-center">
  <div class="row mt-5">
    <!--Die beiden leeren Col Elemente sorgen dafür, dass das Rechteck mit den Textfeldern im Inhalt in der Mitte des Bildschirms angezeigt wird -->
    <div class="col">
    </div>
    <div class="col-6">
      <!--Die Seite wird innerhalb eines Cards angezeigt -->
      <div class="card p-5">
        <h2 class="mb-4">Ihr Password wurde erfolgreich geändert.</h2>
        <center>
          <div class="col py-3">
            <div class="row">
              <div class="col-sm-12">
                <a href="{% url 'edit:settings'%}" class="btn btn-secondary">Zurück zu Einstellungen</a>
              </div>
            </div>
          </div>
        </center>
      </div>
    </div>
    <div class="col"></div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
  integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
  integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
  integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock hauptinhalt%}

edit/templates/edit/change_password_form.html
{% extends "home/base.html"%}
{%load static%}
{% load crispy_forms_tags %}
{% block hauptinhalt %}
<div class="col mt-5 py-5">
  <div class="row mt-5">
    <!--Die beiden leeren Col Elemente sorgen dafür, dass das Rechteck mit den Textfeldern im Inhalt in der Mitte des Bildschirms angezeigt wird -->
    <div class="col">
    </div>
    <div class="col-6">
      <!--Die Seite wird innerhalb eines Cards angezeigt -->
      <div class="card p-5">
        <h2 class="mb-5" style="text-align: center;">Password ändern</h2>
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <center>
            <button class="btn btn-primary mt-3 me-2" name="speichern" type="submit">Speichern</button>
            <a class="btn btn-secondary mt-3" href="{% url 'edit:settings' %}">Zurück</a>
          </center>
        </form>
      </div>
    </div>
    <div class="col"></div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
  integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
  integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
  integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock hauptinhalt %}

edit/templates/edit/deleteAccount.html
{% extends "home/base.html"%}
{%load static%}

{% block hauptinhalt %}
<div class="col py-5 mt-5">
    <div class="row mt-5">
        <!--Die beiden leeren Col Elemente sorgen dafür, dass das Rechteck mit den Textfeldern im Inhalt in der Mitte des Bildschirms angezeigt wird -->
        <div class="col">
        </div>
        <div class="col-6">
            <!--Die Seite wird innerhalb eines Cards angezeigt -->
            <div class="card p-5">
                <h1 class="mb-4">Konto löschen</h1>
                <h5 class="mb-4">Du möchtest dein Konto unwiederruflich löschen? Gib zur Sicherheit bitte dein Passwort
                    ein.</h5>
                <form class="form-inline">
                    <div class="row">
                        <div class="col-12 w-75 mb-3">
                            <label class="form-label mb-3" for="inputEmail4">Passwort</label>
                            <input type="password" class="form-control" id="#" placeholder="****************">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 w-75 mb-3">
                            <label class="form-label mb-3" for="inputEmail4">Passwort wiederholen</label>
                            <input type="password" class="form-control" id="#" placeholder="****************">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <button type="button" class="btn btn-danger me-2">Löschen</button>
                        <a href="{% url 'edit:settings'%}" class="btn btn-primary">Zurück</a>
                    </div>
                </form>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock hauptinhalt %}

edit/templates/edit/editBankAccount.html
{% extends "edit/base.html"%}
{%load static%}
{% load crispy_forms_tags %}
{% block hauptinhalt %}
<div class="col py-5 mt-5">
    <div class="row mt-5">
        <!--Die beiden leeren Col Elemente sorgen dafür, dass das Rechteck mit den Textfeldern im Inhalt in der Mitte des Bildschirms angezeigt wird -->
        <div class="col">
        </div>
        <div class="col-6">
            <!--Die Seite wird innerhalb eines Cards angezeigt -->
            <div class="card p-5">
                <h1 class="mb-4">Konto erstellen</h1>
                {% for message in messages %}
                <div class="alert alert-success">
                    <a class="close" href="#" data-dismiss="alert">×</a>
                    {{ message }}
                </div>
                {% endfor %}
                <form class="form-inline" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6">
                            {{form.name|as_crispy_field}}
                        </div>
                        <div class="col-sm-6">
                            {{form.bank|as_crispy_field}}
                        </div>
                    </div>
                    <p></p>
                    <div class="row">
                        <div class="col-sm-6">
                            {{form.iban|as_crispy_field}}
                        </div>
                        <div class="col-sm-6">
                            {{form.bic|as_crispy_field}}
                        </div>
                    </div>
                    <p></p>
                    <div class="row">
                        <div class="col-sm-6">
                            {{form.kontostand|as_crispy_field}}
                        </div>
                    </div>
                    <br />
                    <div class="col py-3">
                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-success me-2">Speichern</button>
                                <!-- Submit-Button statt Link, um Speichern auszulösen-->
                                <a href="{% url 'home:accounts'%}" class="btn btn-primary">Zurück zur Übersicht</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock hauptinhalt %}

edit/templates/edit/editBankData.html
{% extends "home/base.html"%}
{%load static%}

{% block hauptinhalt %}
<div class="col py-5 mt-5">
    <div class="row mt-5">
        <!--Die Seite wird innerhalb eines Cards angezeigt -->
        <div class="col">
        </div>
        <div class="col-6">
            <!--Die beiden leeren Col Elemente sorgen dafür, dass das Rechteck mit den Textfeldern im Inhalt in der Mitte des Bildschirms angezeigt wird -->
            <div class="card p-5">
                <h1 class="mb-4">Bankdaten bearbeiten</h1>
                <form class="form-inline">
                    <div class="row">
                        <div class="col-sm-6">
                            <label for="inputEmail4">Kontoinhaber</label>
                            <p></p>
                            <input type="email" class="form-control" id="inputInhaber">
                        </div>
                        <div class="col-sm-6">
                            <label for="inputEmail4">Bank</label>
                            <p></p>
                            <input type="email" class="form-control" id="inputEmail4">
                        </div>
                    </div>
                    <p></p>
                    <div class="row">
                        <div class="col-sm-6">
                            <label for="inputPassword4">Kontonummer</label>
                            <p></p>
                            <input type="password" class="form-control" id="inputPassword4">
                        </div>
                        <div class="col-sm-6">
                            <label for="inputAddress">IBAN</label>
                            <p></p>
                            <input type="text" class="form-control" id="inputAddress">
                        </div>
                    </div>
                    <p></p>
                    <div class="row">
                        <div class="col-sm-6">
                            <label for="inputAddress2">BLZ</label>
                            <p></p>
                            <input type="text" class="form-control" id="inputAddress2">
                        </div>
                        <div class="col-sm-6">
                            <label for="inputCity">BIC</label>
                            <p></p>
                            <input type="text" class="form-control" id="inputCity">
                        </div>
                    </div>
                </form>
                <br />

                <div class="col py-3">
                    <div class="row">
                        <div class="col-sm-12">
                            <button type="button" class="btn btn-primary me-2">Speichern</button>
                            <a href="{% url 'edit:settings'%}" class="btn btn-secondary">Zurück</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
    crossorigin="anonymous"></script>
{% endblock hauptinhalt %}

edit/templates/edit/settings.html
{% extends "home/base.html"%}
{%load static%}

{% block hauptinhalt %}
<!--Die Einstellungen werden innerhalb einer Bootstrap-Card angezeigt -->
<div class="col py-5">
   <div class="row">
      <div class="col">
      </div>
      <div class="col-6">
         <div class="card p-5">
            <h1 class="mb-4">Einstellungen</h1>
            <!--Die Einzelnen Einstellungsmerkmale werden ebenfalls innerhalb eines Cards platziert, damit sie ordentlich und sauber aussehen -->
            <div class="card mb-4">
               <div class="card-body">
                  <h5 class="card-title"> <i class="bi bi-people-fill"></i> Kontakte <a href="{% url 'home:contacts'%}"
                        class="btn btn-primary" id="a">Bearbeiten</a></h5>
               </div>
            </div>
            <p></p>
            <div class="card mb-4">
               <div class="card-body">
                  <h5 class="card-title"> <i class="bi bi-bank"></i> Bankdaten <a href="{% url 'edit:editBankData'%}"
                        class="btn btn-primary" id="a">Bearbeiten</a></h5>
               </div>
            </div>
            <p></p>
            <div class="card mb-4">
               <div class="card-body">
                  <h5 class="card-title"> <i class="bi bi-lock-fill"></i> Passwort <a
                        href="{% url 'edit:change_password_form'%}" class="btn btn-primary" name="pwAendern" id="a">Ändern</a></h5>
               </div>
            </div>
            <p></p>
            <div class="card mb-4">
               <div class="card-body">
                  <h5 class="card-title"> <i class="bi bi-person-x"></i> Konto löschen <a
                        href="{% url 'edit:deleteAccount'%}" class="btn btn-primary" id="a">Löschen</a></h5>
               </div>
            </div>
         </div>
      </div>
      <div class="col"></div>
   </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
   integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
   integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
   integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
   integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
   crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
   integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
   integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock hauptinhalt %}